import Head from 'next/head'
import Main from '../components/main/Main'
import Navbar from '../components/navbar/Navbar'
import Sidebar from '../components/sidebar/Sidebar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>YouTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/app.ico" />
      </Head>

      <div>
        <Navbar />
        <div className='flex'>
          <Sidebar page='Home' />
          <Main type='random' />
        </div>
      </div>

    </div>
  )
}
