import Head from 'next/head'
import React, { useState } from 'react'
import { useDispatch } from 'react-redux'
import axios from '../axios'
import { useRouter } from 'next/router'
import { loginFailure, loginStart, loginSuccess } from '../redux/userSlice'
import toast from 'react-hot-toast'
import { signInWithPopup } from 'firebase/auth'
import { auth, provider } from '../firebase'

const Signin = () => {
    const [signinForm, setSigninForm] = useState({ email: '', password: '' })
    const [signupForm, setSignupForm] = useState({ username: '', email: '', password: '' })
    const dispatch = useDispatch()
    const router = useRouter()

    const signinChange = (e) => {
        setSigninForm((prev) => ({ ...prev, [e.target.name]: e.target.value }))
    }
    const handleSigin = async (e) => {
        e.preventDefault()
        dispatch(loginStart())
        const loading = toast.loading('logging in...')
        try {
            const res = await axios.post('/auth/signin', {
                email: signinForm.email,
                password: signinForm.password
            }, { withCredentials: true })
            console.log(res)
            dispatch(loginSuccess(res.data))
            router.push('/')
            toast.success('Logged in', { id: loading })
        } catch (e) {
            dispatch(loginFailure())
        }
    }

    const handleSiginWithGoogle = () => {
        signInWithPopup(auth, provider)
            .then(async (result) => {
                const loading = toast.loading('logging in...')
                dispatch(loginStart())
                const user = result.user;
                const res = await axios.post('/auth/google', {
                    username: user.displayName,
                    email: user.email,
                    img: user.photoURL
                })
                dispatch(loginSuccess(res.data))
                router.push('/')
                toast.success('Logged in', { id: loading })
            }).catch((error) => {
                dispatch(loginFailure())
            });
    }

    return (
        <div className='w-full h-screen bg-gray-50 flex items-center justify-center flex-col'>
            <Head>
                <title>YouTube - Sign in</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/app.ico" />
            </Head>

            <div></div>

            <div className='flex items-center justify-center mb-5'>
                <img className='w-32 h-14' src="/youtube.svg" alt="" />
            </div>

            <div className="flex bg-white w-96 px-6 py-4 flex-col rounded shadow">
                <h1 className='text-center my-1 font-semibold uppercase text-gray-700 text-lg'>Sign in</h1>
                <div className="flex flex-col">
                    <form className="flex flex-col flex-1 space-y-3" onSubmit={handleSigin}>
                        <span></span>
                        <input required onChange={signinChange} name='email' className='outline-none py-2 px-3 rounded bg-gray-100 border border-gray-200' type="email" placeholder='Email' />
                        <input required onChange={signinChange} name='password' className='outline-none py-2 px-3 rounded bg-gray-100 border border-gray-200' type="password" placeholder='Password' />
                        <button className='bg-blue-50 text-blue-600 py-1 rounded border-2 border-blue-600 font-semibold hover:bg-blue-100 active:bg-blue-200'>Sign in</button>
                    </form>
                    <div onClick={handleSiginWithGoogle} className="flex my-2 bg-blue-600 rounded p-1 items-center shadow cursor-pointer hover:bg-blue-700">
                        <img className='w-8 h-8 bg-white rounded-l p-1' src="https://cdn-icons-png.flaticon.com/512/2702/2702602.png" alt="" />
                        <span className='flex-1 text-center text-white font-semibold'>Continue with google</span>
                    </div>
                </div>

                <h3 className='w-full text-center font-semibold uppercase text-gray-700'>or</h3>

                <div className="flex">
                    <form className="flex flex-col flex-1 space-y-3">
                        <span></span>
                        <input name='username' className='outline-none py-2 px-3 rounded bg-gray-100 border border-gray-200' type="text" placeholder='Username' />
                        <input name='email' className='outline-none py-2 px-3 rounded bg-gray-100 border border-gray-200' type="email" placeholder='Email' />
                        <input name='password' className='outline-none py-2 px-3 rounded bg-gray-100 border border-gray-200' type="password" placeholder='Password' />
                        <button className='bg-sky-50 text-sky-600 py-1 rounded border-2 border-sky-600 font-semibold hover:bg-sky-600 hover:text-white shadow shadow-sky-200'>Sign up</button>
                    </form>
                </div>
            </div>

        </div>
    )
}

export default Signin